//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_of_debts
    {
        public int Id { get; set; }
        public int Address { get; set; }
        public int Flat { get; set; }
        public int Owner { get; set; }
        public string Telephone { get; set; }
        public double Water { get; set; }
        public Nullable<double> Electricpower { get; set; }
    
        public virtual List_of_housing_stock List_of_housing_stock { get; set; }
        public virtual Owner Owner1 { get; set; }
    }
}
