//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
        private static Entities _context;
        public static Entities GetContext()
        {
            if (_context == null)
            {
                _context = new Entities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Applications> Applications { get; set; }
        public DbSet<HistoryJob> HistoryJob { get; set; }
        public DbSet<List_of_debts> List_of_debts { get; set; }
        public DbSet<List_of_housing_stock> List_of_housing_stock { get; set; }
        public DbSet<Owner> Owner { get; set; }
        public DbSet<Payment_Report> Payment_Report { get; set; }
        public DbSet<Rate> Rate { get; set; }
        public DbSet<ReportOfJob> ReportOfJob { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Service> Service { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<StatusReportJob> StatusReportJob { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
