//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public Owner()
        {
            this.List_of_debts = new HashSet<List_of_debts>();
            this.Payment_Report = new HashSet<Payment_Report>();
        }
    
        public string Owner1 { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<List_of_debts> List_of_debts { get; set; }
        public virtual ICollection<Payment_Report> Payment_Report { get; set; }
    }
}
