//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Report
    {
        public int ID { get; set; }
        public int Owner { get; set; }
        public int Address { get; set; }
        public int Flat { get; set; }
        public string Period { get; set; }
        public double Accrued { get; set; }
        public Nullable<double> Paid_for { get; set; }
    
        public virtual List_of_housing_stock List_of_housing_stock { get; set; }
        public virtual Owner Owner1 { get; set; }
    }
}
