//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportOfJob
    {
        public ReportOfJob()
        {
            this.HistoryJob = new HashSet<HistoryJob>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Application { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual ICollection<HistoryJob> HistoryJob { get; set; }
        public virtual StatusReportJob StatusReportJob { get; set; }
    }
}
