//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusReportJob
    {
        public StatusReportJob()
        {
            this.ReportOfJob = new HashSet<ReportOfJob>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<ReportOfJob> ReportOfJob { get; set; }
    }
}
